Wait on entire kafka config since it can take awhile to appear in config

diff --git a/tests/kuttl/test-cyndi-strimzi/02-json-asserts.yaml b/tests/kuttl/test-cyndi-strimzi/02-json-asserts.yaml
--- a/tests/kuttl/test-cyndi-strimzi/02-json-asserts.yaml
+++ b/tests/kuttl/test-cyndi-strimzi/02-json-asserts.yaml
@@ -5,12 +5,13 @@ commands:
 - script: >
     for i in {1..10}; do
     kubectl get secret -n test-cyndi-strimzi-kafka test-cyndi-strimzi-host-inventory-db-cyndi -o json > /tmp/host-inventory-db-cyndi-secret &&
+    kubectl get secret -n test-cyndi-strimzi-kafka test-cyndi-strimzi-myapp-db-cyndi -o json > /tmp/myapp-db-cyndi-secret &&
     kubectl get secret -n test-cyndi-strimzi host-inventory-db -o json > /tmp/host-inventory-db-secret &&
     kubectl get secret -n test-cyndi-strimzi myapp-db -o json > /tmp/myapp-db-secret &&
     kubectl get cyndipipeline -n test-cyndi-strimzi -o json > /tmp/cyndipipeline &&
     exit 0 || sleep 1;
     done;
-    echo "Expected secrets not found"; exit 1
+    echo "Expected secrets/cyndipipeline not found"; exit 1
 - script: jq '.data' /tmp/host-inventory-db-secret > /tmp/host-inventory-db-secret-data
 - script: jq '.data' /tmp/host-inventory-db-cyndi-secret > /tmp/host-inventory-db-cyndi-secret-data
 - script: EXPECTED=$(jq '.data["hostname"]' /tmp/host-inventory-db-secret); jq -e '.data["db.host"] == '$EXPECTED /tmp/host-inventory-db-cyndi-secret
