Fix the more complex scenarios

diff --git a/tests/kuttl/test-cyndi-strimzi/02-json-asserts.yaml b/tests/kuttl/test-cyndi-strimzi/02-json-asserts.yaml
--- a/tests/kuttl/test-cyndi-strimzi/02-json-asserts.yaml
+++ b/tests/kuttl/test-cyndi-strimzi/02-json-asserts.yaml
@@ -2,12 +2,15 @@
 apiVersion: kuttl.dev/v1beta1
 kind: TestStep
 commands:
-- script: for i in {1..10}; do kubectl get secret --namespace=test-cyndi-strimzi puptoo && exit 0 || sleep 1; done; echo "Secret not found"; exit 1
-- script: kubectl get secret -n test-cyndi-strimzi-kafka test-cyndi-strimzi-host-inventory-db-cyndi -o json > /tmp/host-inventory-db-cyndi-secret
-- script: kubectl get secret -n test-cyndi-strimzi-kafka test-cyndi-strimzi-myapp-db-cyndi -o json > /tmp/myapp-db-cyndi-secret
-- script: kubectl get secret -n test-cyndi-strimzi host-inventory-db -o json > /tmp/host-inventory-db-secret
-- script: kubectl get secret -n test-cyndi-strimzi myapp-db -o json > /tmp/myapp-db-secret
-- script: kubectl get cyndipipeline -n test-cyndi-strimzi -o json > /tmp/cyndipipeline
+- script: >
+    for i in {1..10}; do
+    kubectl get secret -n test-cyndi-strimzi-kafka test-cyndi-strimzi-host-inventory-db-cyndi -o json > /tmp/host-inventory-db-cyndi-secret &&
+    kubectl get secret -n test-cyndi-strimzi host-inventory-db -o json > /tmp/host-inventory-db-secret &&
+    kubectl get secret -n test-cyndi-strimzi myapp-db -o json > /tmp/myapp-db-secret &&
+    kubectl get cyndipipeline -n test-cyndi-strimzi -o json > /tmp/cyndipipeline &&
+    exit 0 || sleep 1;
+    done;
+    echo "Expected secrets not found"; exit 1
 - script: jq '.data' /tmp/host-inventory-db-secret > /tmp/host-inventory-db-secret-data
 - script: jq '.data' /tmp/host-inventory-db-cyndi-secret > /tmp/host-inventory-db-cyndi-secret-data
 - script: EXPECTED=$(jq '.data["hostname"]' /tmp/host-inventory-db-secret); jq -e '.data["db.host"] == '$EXPECTED /tmp/host-inventory-db-cyndi-secret
diff --git a/tests/kuttl/test-kafka-msk/02-json-asserts.yaml b/tests/kuttl/test-kafka-msk/02-json-asserts.yaml
--- a/tests/kuttl/test-kafka-msk/02-json-asserts.yaml
+++ b/tests/kuttl/test-kafka-msk/02-json-asserts.yaml
@@ -2,7 +2,13 @@
 apiVersion: kuttl.dev/v1beta1
 kind: TestStep
 commands:
-- script: for i in {1..10}; do kubectl get secret --namespace=test-kafka-msk puptoo && exit 0 || sleep 1; done; echo "Secret not found"; exit 1
+- script: >
+    for i in {1..10}; do
+    kubectl get secret --namespace=test-kafka-msk test-kafka-msk-connect &&
+    kubectl get secret --namespace=test-kafka-msk test-kafka-msk-cluster-ca-cert &&
+    exit 0 || sleep 1;
+    done;
+    echo "Expected secrets not found"; exit 1
 - script: kubectl get secret --namespace=test-kafka-msk test-kafka-msk-connect -o json > /tmp/test-kafka-msk-user
 - script: kubectl get secret --namespace=test-kafka-msk test-kafka-msk-cluster-ca-cert -o json > /tmp/test-kafka-msk-cluster-ca-cert
 
