Improve sleep logic and fix intermittent flakes in kuttl tests (#1252)
* Improve sleep logic in kuttl tests

* No need to check if the namespace exists

* Fix the more complex scenarios

* Split up long line into multiline

* Wait on entire kafka config since it can take awhile to appear in config

* Retry wget in get_request_edge

* Remove unused lines

* Revert test-cyndi-strimzi and mark as TODO

* Use http retries everywhere to avoid flakes

* Further tweaks

* Adjust comment length

* Adjustable retries

* Make test-config-secret-restarter more predictable

* Final generation is unpredictable, modify script to do a >= check

diff --git a/tests/kuttl/test-kafka-app-interface/04-json-asserts.yaml b/tests/kuttl/test-kafka-app-interface/04-json-asserts.yaml
--- a/tests/kuttl/test-kafka-app-interface/04-json-asserts.yaml
+++ b/tests/kuttl/test-kafka-app-interface/04-json-asserts.yaml
@@ -2,11 +2,14 @@
 apiVersion: kuttl.dev/v1beta1
 kind: TestStep
 commands:
-- script: sleep 5
-- script: kubectl get secret --namespace=test-kafka-app-interface puptoo -o json > /tmp/test-kafka-app-interface
-- script: jq -r '.data["cdappconfig.json"]' < /tmp/test-kafka-app-interface | base64 -d > /tmp/test-kafka-app-interface-json
-
-- script: jq -r '.kafka.brokers[0].hostname == "test-kafka-app-interface-kafka-bootstrap.test-kafka-app-interface.svc"' -e < /tmp/test-kafka-app-interface-json
-- script: jq -r '.kafka.brokers[0].port == 9093' -e < /tmp/test-kafka-app-interface-json
-- script: jq -r '.kafka.brokers[0].cacert == "cacert"' -e < /tmp/test-kafka-app-interface-json
-- script: jq -r '.kafka.brokers[0].securityProtocol == "SSL"' -e < /tmp/test-kafka-app-interface-json
+- script: >
+    for i in {1..15}; do
+    kubectl get secret --namespace=test-kafka-app-interface puptoo -o json > /tmp/test-kafka-app-interface &&
+    jq -r '.data["cdappconfig.json"]' < /tmp/test-kafka-app-interface | base64 -d > /tmp/test-kafka-app-interface-json &&
+    jq -r '.kafka.brokers[0].hostname == "test-kafka-app-interface-kafka-bootstrap.test-kafka-app-interface.svc"' -e < /tmp/test-kafka-app-interface-json &&
+    jq -r '.kafka.brokers[0].port == 9093' -e < /tmp/test-kafka-app-interface-json &&
+    jq -r '.kafka.brokers[0].cacert == "cacert"' -e < /tmp/test-kafka-app-interface-json &&
+    jq -r '.kafka.brokers[0].securityProtocol == "SSL"' -e < /tmp/test-kafka-app-interface-json &&
+    exit 0 || sleep 1;
+    done;
+    echo "Expected kafka topics config not found in cdappconfig.json"; exit 1
